import type{Exercise,SetLog,Settings,Recommendation,Session}from'./types';
export const roundTo=(n:number,step=2.5)=>Math.round(n/step)*step;export const roundLoad=(n:number)=>roundTo(n,2.5);
export function recommend(ex:Exercise,sets:SetLog[],s:Settings,increment=2.5):Recommendation{if(ex.type==='power'||ex.type==='body'||!sets?.length)return null;const valid=sets.filter(x=>x.done!==false&&Number.isFinite(+x.weight));if(!valid.length)return null;const w=+valid.at(-1)!.weight;if(valid.some(x=>+x.rir===0))return{w:roundTo(w*(1-s.deload/100),increment),label:'Bajá carga: hubo una serie en RIR 0',kind:'down'};const allTop=valid.length>=ex.sets&&valid.every(x=>+x.reps>=ex.max&&+x.rir>=1&&+x.rir<=3);if(allTop){const p=ex.type==='lower'?s.lower:s.upper;return{w:roundTo(w*(1+p/100),increment),label:'Todas las series sólidas. Subí carga.',kind:'up'}}return{w,label:'Mantené la carga y ganá reps con buena técnica',kind:'same'}}
export const volume=(s:Session)=>s.logs.reduce((a,l)=>a+l.sets.reduce((b,x)=>b+(+x.weight||0)*(+x.reps||0),0),0);
export const e1rm=(w:number,r:number)=>w&&r?Math.round(w*(1+r/30)*10)/10:0;
export function bmi(weight?:number,height?:number){if(!weight||!height)return null;return Math.round(weight/((height/100)**2)*10)/10}
export function bodyTrend(entries:{date:string;weight:number}[]){if(entries.length<2)return null;const sorted=[...entries].sort((a,b)=>a.date.localeCompare(b.date));return Math.round((sorted.at(-1)!.weight-sorted[0].weight)*10)/10}
export type ExerciseMemory={exerciseId:string;exposures:number;lastDate?:string;lastSets:SetLog[];bestE1rm:number;bestWeight:number;targetWeight?:number;targetReps?:number[]};
export function exerciseMemory(exerciseId:string,sessions:Session[]):ExerciseMemory{const hits=sessions.flatMap(s=>(s.logs||[]).filter(l=>l.id===exerciseId).map(l=>({date:s.date,log:l}))).sort((a,b)=>a.date.localeCompare(b.date));let bestE1rm=0,bestWeight=0;for(const h of hits)for(const set of h.log.sets||[]){bestWeight=Math.max(bestWeight,set.weight||0);bestE1rm=Math.max(bestE1rm,e1rm(set.weight||0,set.reps||0))}const last=hits.at(-1);return{exerciseId,exposures:hits.length,lastDate:last?.date,lastSets:last?.log.sets||[],bestE1rm,bestWeight,targetWeight:last?.log.next?.w}}
export function nextRepTargets(sets:SetLog[],min:number,max:number){if(!sets.length)return[];return sets.map(s=>Math.min(max,Math.max(min,s.reps+(s.rir>=1?1:0))))}
export function plannedSoFar(now=new Date()){const monday=new Date(now);const d=(now.getDay()+6)%7;monday.setDate(now.getDate()-d);monday.setHours(0,0,0,0);return[1,2,4,5].filter(day=>{const x=new Date(monday);x.setDate(monday.getDate()+day-1);return x<=now}).length}
export const localDateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export function missedPlannedDates(sessions:Session[],activities:{date:string;type:string}[],since?:string,now=new Date()){if(!since)return[];const start=new Date(since);start.setHours(0,0,0,0);const end=new Date(now);end.setHours(0,0,0,0);const done=new Set([...sessions.map(s=>localDateKey(new Date(s.date))),...activities.filter(a=>a.type==='gym').map(a=>localDateKey(new Date(a.date)))]);const out:string[]=[];for(const d=new Date(start);d<end;d.setDate(d.getDate()+1)){if([1,2,4,5].includes(d.getDay())&&!done.has(localDateKey(d)))out.push(localDateKey(d))}return out}
